# .github/workflows/deploy.yml
name: Deploy Nginx Docker Image to EC2

on:
  push:
    branches:
      - main  # Trigger on push to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: "ap-southeast-1a"  # Set your preferred AWS region
      IMAGE_NAME: "hasanroo10/nginx-hsn-test"

    steps:
    # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v2

    # Build the Docker image
    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME .

    # Login to Docker Hub
    - name: Login to Docker Hub
      run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

    # Push the Docker image to Docker Hub
    - name: Push Docker Image to Docker Hub
      run: docker push $IMAGE_NAME

    # SSH into the EC2 instance and deploy the Docker container
    - name: Deploy Docker Image to EC2
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu  # Adjust based on your EC2 instance setup
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          # Update the instance and install Docker if not installed
          sudo apt update
          sudo apt install -y docker.io
          
          # Stop and remove any existing containers running on port 80
          docker ps -q --filter "ancestor=$IMAGE_NAME" | grep -q . && docker stop $(docker ps -q --filter "ancestor=$IMAGE_NAME") && docker rm $(docker ps -q --filter "ancestor=$IMAGE_NAME")
          
          # Pull the new image from Docker Hub
          docker pull $IMAGE_NAME
          
          # Run the Docker container, mapping to port 80
          docker run -d -p 80:80 $IMAGE_NAME
